// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKsCG-YsiZ5UfcXuKW0O03o4OPdztESjw',
    appId: '1:1001077070724:web:1d4018e78f1c05be8a9bd1',
    messagingSenderId: '1001077070724',
    projectId: 'asset-tracker-d3c21',
    authDomain: 'asset-tracker-d3c21.firebaseapp.com',
    storageBucket: 'asset-tracker-d3c21.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0vEDuBND-Bp99K9J7eefH4dPILGC3eho',
    appId: '1:1001077070724:android:06c6ff91f78ec3b58a9bd1',
    messagingSenderId: '1001077070724',
    projectId: 'asset-tracker-d3c21',
    storageBucket: 'asset-tracker-d3c21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbOfEhd5xA6JxoKuwl1E6WewSP81_qZ0A',
    appId: '1:1001077070724:ios:309c5431786017308a9bd1',
    messagingSenderId: '1001077070724',
    projectId: 'asset-tracker-d3c21',
    storageBucket: 'asset-tracker-d3c21.firebasestorage.app',
    iosBundleId: 'com.example.assetTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbOfEhd5xA6JxoKuwl1E6WewSP81_qZ0A',
    appId: '1:1001077070724:ios:309c5431786017308a9bd1',
    messagingSenderId: '1001077070724',
    projectId: 'asset-tracker-d3c21',
    storageBucket: 'asset-tracker-d3c21.firebasestorage.app',
    iosBundleId: 'com.example.assetTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKsCG-YsiZ5UfcXuKW0O03o4OPdztESjw',
    appId: '1:1001077070724:web:cf854e545ab4dd2b8a9bd1',
    messagingSenderId: '1001077070724',
    projectId: 'asset-tracker-d3c21',
    authDomain: 'asset-tracker-d3c21.firebaseapp.com',
    storageBucket: 'asset-tracker-d3c21.firebasestorage.app',
  );
}
