name: asset_tracker_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #flutter_secure_storage
  flutter_secure_storage: ^9.2.4

  #BLOC
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6

  #web_socket_channel
  web_socket_channel: ^3.0.1

  #FIREBASE
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  #Firebase Firestore
  cloud_firestore: ^5.6.3
  intl: ^0.20.2

  #CHARTS
  fl_chart: ^0.65.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:


  uses-material-design: true

  