name: asset_tracker_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #FIREBASE
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0

  #BLOC
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6

  #web_socket_channel
  web_socket_channel: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:


  uses-material-design: true

  