import 'package:asset_tracker_app/utils/enums/currency_type_enum.dart';

final priorityOrder = [
  CurrencyType.ALTIN,
  CurrencyType.KULCEALTIN,
  CurrencyType.EURTRY,
  CurrencyType.EURUSD,
  CurrencyType.ONS,
  CurrencyType.GBPTRY,
  CurrencyType.AYAR22,
  CurrencyType.AYAR14,
  CurrencyType.CEYREK_YENI,
  CurrencyType.CEYREK_ESKI,
  CurrencyType.YARIM_YENI,
  CurrencyType.YARIM_ESKI,
  CurrencyType.TEK_YENI,
  CurrencyType.TEK_ESKI,
  CurrencyType.ATA_YENI,
  CurrencyType.ATA_ESKI,
  CurrencyType.ATA5_YENI,
  CurrencyType.ATA5_ESKI,
  CurrencyType.GUMUSTRY,
  CurrencyType.GREMSE_YENI,
  CurrencyType.GREMSE_ESKI,
  CurrencyType.PLATIN,
  CurrencyType.BILEZIK,
];

/// Only assets in this list will be shown on the home screen.
const visibleAssetCodes = [
  'ALTIN',
  'KULCEALTIN',
  'EURTRY',
  'ONS',
  'GBPTRY',
  'AYAR22',
  'AYAR14',
  'CEYREK_YENI',
  'CEYREK_ESKI',
  'YARIM_YENI',
  'YARIM_ESKI',
  'TEK_YENI',
  'TEK_ESKI',
  'ATA_YENI',
  'ATA_ESKI',
  'ATA5_YENI',
  'ATA5_ESKI',
  'GREMSE_YENI',
  'GREMSE_ESKI',
  'PLATIN',
  'EURUSD',
];

/// Only assets in this list will be shown in the add asset screen.
const selectableAssetCodes = [
  'ALTIN',
  'KULCEALTIN',
  'GBPTRY',
  'AYAR22',
  'AYAR14',
  'CEYREK_YENI',
  'CEYREK_ESKI',
  'YARIM_YENI',
  'YARIM_ESKI',
  'TEK_YENI',
  'TEK_ESKI',
  'ATA_YENI',
  'ATA_ESKI',
  'ATA5_YENI',
  'ATA5_ESKI',
  'GREMSE_YENI',
  'GREMSE_ESKI',
  'PLATIN',
  'EURTRY',
  'BILEZIK',
];
